# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_cover_photo',
        ),
    ]
