# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_artwork_is_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='artwork/%Y/%m'),
        ),
    ]
