# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170527_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/%Y/%m/'),
        ),
    ]
