# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170527_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
