# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20170528_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='alt_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='alt_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='alt_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/%Y/%m/'),
        ),
    ]
